### PR TITLE
Patches for `dev/giss-gc-iso` branch

### PR DESCRIPTION
**Pull request by joewallwork**
Hi @ltmurray. I tried running with your branches but noticed you are missing a few patches that we added to the `develop` branch. Commit 2beb3ef9854a87b547f3092978e9d298a179f07a caused an issue for me in particular.

This PR should update your `dev/giss-gc-iso` branch accordingly.

### CODE REVIEW

**Comment by joewallwork** [comment]
You might want to check if we still want the contents of 77e7648. i.e., do we still want to be "purposefully breaking" the branch?

**Comment by ltmurray** [comment]
No, these changes are superseded, and should be removed. This is from when we were incorrectly compiling GEOS-Chem with the MODEL_CLASSIC preprocessing statement. Now we are correctly only compiling with MODEL_GISS, therefore, no longer breaking the default (MODEL_CLASSIC) compilation process.

**Comment by ltmurray** [comment]
Same goes for for 2beb3ef98, b79e082b9, and 7c06462fd. I'm not sure if 83409f8b2 is still necessary with the updated compilation framework, but I haven't encountered any issues on my systems.

**Comment by joewallwork** [comment]
Ahh got it, thanks @ltmurray. I was missing this patch on the GISS-GC side:
```
diff --git a/model/geos-chem/CMakeLists.txt b/model/geos-chem/CMakeLists.txt
index ab4f94c..db123df 100644
--- a/model/geos-chem/CMakeLists.txt
+++ b/model/geos-chem/CMakeLists.txt
@@ -34,7 +34,7 @@ include(GC-Helpers)
 #-----------------------------------------------------------------------------
 get_repo_version(GC_REPO_VERSION ${CMAKE_CURRENT_SOURCE_DIR})
 message("=================================================================")
-message("GCClassic ${PROJECT_VERSION} (superproject wrapper)")
+message("GISS-GC ${PROJECT_VERSION} (superproject wrapper)")
 message("Current status: ${GC_REPO_VERSION}")
 message("=================================================================")
 
@@ -222,7 +222,7 @@ if(NOT GC_EXTERNAL_CONFIG)
    gc_pretty_print(VARIABLE RUNDIR)
 
    # Configure for GCClassic
-   include(GC-ConfigureClassic)
+   include(GC-ConfigureGISS-GC)
    configureGCClassic()
 
 endif()
```

**Pull request closed without merging**
